### ISSUE TITLE
OpenCV.mk and opencv header files are missing

### ISSUE THREAD

**Issue by rbarara** [cmauri/eva_facial_mouse#12]
During compile - I get an error for missing OpenCV.mk file. When I tried to look for the file - there is no file with that name in any of the directories included in the package on git repository. 

I downloaded opencv package from git but that also does not have all the related files.

Can some one please help me with the above ?

**Comment by cmauri** [comment]
Hi
Check compilation instructions here:
https://github.com/cmauri/eva_facial_mouse/blob/develop/INSTALL

**Comment by rbarara** [comment]
Thanks for pointing to install. After setting environment variables, I get the following error (seems like :
android_native_app_glue.c:233: error: undefined reference to 'android_main' is the issue).. Am I missing a library ?

Android NDK: android-9 is unsupported. Using minimum supported version android-14.    
Android NDK: WARNING: APP_PLATFORM android-14 is higher than android:minSdkVersion 1 in src/main/AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-14. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
[armeabi] Prebuilt       : libopencv_java3.so <= /Users/rajan/opencv/sdk//native/jni/../libs/armeabi/
[armeabi] Install        : libopencv_java3.so => libs/armeabi/libopencv_java3.so
[armeabi] Compile++ thumb: visionpipeline <= crvimage.cpp
[armeabi] Compile++ thumb: visionpipeline <= timeutil.cpp
[armeabi] Compile++ thumb: visionpipeline <= normroi2.cpp
[armeabi] Compile++ thumb: visionpipeline <= facedetection.cpp
[armeabi] Compile++ thumb: visionpipeline <= visionpipeline.cpp
[armeabi] Compile++ thumb: visionpipeline <= visionpipeline_jni.cpp
[armeabi] Compile thumb  : android_native_app_glue <= android_native_app_glue.c
[armeabi] StaticLibrary  : libandroid_native_app_glue.a
[armeabi] SharedLibrary  : libvisionpipeline.so

/Users/rajan/Library/Android/sdk/ndk-bundle/sources/android/native_app_glue/android_native_app_glue.c:233: error: undefined reference to 'android_main'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [src/main/obj/local/armeabi/libvisionpipeline.so] Error 1

:eviacam:ndkBuild FAILED

FAILURE: Build failed with an exception.

**Comment by cmauri** [comment]
See https://github.com/cmauri/eva_facial_mouse/issues/13
