### ISSUE TITLE
Gradle error! Please help

### ISSUE THREAD

**Issue by bublitrubli** [cmauri/eva_facial_mouse#26]
Hello,

I have this error when opening the project in Android Studio. My system is Mac.

Error:Project :eviacam declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :WizarDroid:wizardroid.

In Gradle build it says: Error:A problem occurred configuring project ':eviacam'. > Could not resolve all dependencies for configuration ':eviacam:_debugApk'.

--------------------
I installed all sdks and ndks. Cloned the project. 
Created a text file with 

ndk.dir=/Users/deniskulikov/Library/Android/sdk/ndk-bundle
sdk.dir=/Users/deniskulikov/Library/Android/sdk

(path is correct according to Android studio preferences.) 

Named it local.properties and placed it in eva facial mouse folder. I can see it in Android Studio. It is in the same folder as settings.gradle so should be fine

-------------------

Downloaded Android Opencv, unzipped it and created environment. 

TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/hh/gqrf_p5x5l7c_qh359vq2zcr0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.LmYZIsJYiy/Render
TERM_PROGRAM_VERSION=400
TERM_SESSION_ID=7527ECB3-532E-4E59-8629-FBDCB52FD519
USER=deniskulikov
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.FrsY1CdhRJ/Listeners
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
PWD=/Users/deniskulikov
LANG=en_US.UTF-8
XPC_FLAGS=0x0

###  **OPENCV_ANDROID_SDK=/Users/deniskulikov/Downloads/OpenCV-android-sdk/sdk**

XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/deniskulikov
LOGNAME=deniskulikov
_=/usr/bin/env

--------------------------

**my settings.gradle says:**

include ':opencv'
include ':eviacam_api'
include ':input_method_aidl'
include ':eviacam'
include ':eviacam_api_demo'
include ':softkeyboard'
include ':WizarDroid:wizardroid'

**build.gradle says:**

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

Then opened the project and got the error. 

What can I do???

Thank you!

**Comment by cmauri** [comment]
Did you follow the INSTALL instructions?

**Comment by bublitrubli** [comment]
Yes. In my error message above i described what i did and i followed the install file, so im not sure what i did wrong.

**Comment by cmauri** [comment]
It seems as if submodules were not cloned. Did you run:

git clone **--recursive** https://github.com/cmauri/eva_facial_mouse.git

to clone eva and all submodules?

**Comment by bublitrubli** [comment]
Okay, it seems like its working now. I did not include RECURSIVE. 

Thank you for your help!
