### ISSUE TITLE
Please Help - Error Build APK

### ISSUE THREAD

**Issue by jpablocas** [cmauri/eva_facial_mouse#34]
Please Help - Error:Execution failed for task ':eviacam:ndkBuild'. > Process 'command 'C:\Users\****\AppData\Local\Android\Sdk\ndk\r13b/ndk-build.cmd'' finished with non-zero exit value 2
very interesting project !!!!

**Comment by sowamaciej** [comment]
@jpablocas  do you fixed the issue? Actually have the same error
